# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class OrderInfoOrders(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, order: str=None, amount: int=None):  # noqa: E501
        """OrderInfoOrders - a model defined in Swagger

        :param order: The order of this OrderInfoOrders.  # noqa: E501
        :type order: str
        :param amount: The amount of this OrderInfoOrders.  # noqa: E501
        :type amount: int
        """
        self.swagger_types = {
            'order': str,
            'amount': int
        }

        self.attribute_map = {
            'order': 'order',
            'amount': 'amount'
        }
        self._order = order
        self._amount = amount

    @classmethod
    def from_dict(cls, dikt) -> 'OrderInfoOrders':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The OrderInfo_orders of this OrderInfoOrders.  # noqa: E501
        :rtype: OrderInfoOrders
        """
        return util.deserialize_model(dikt, cls)

    @property
    def order(self) -> str:
        """Gets the order of this OrderInfoOrders.


        :return: The order of this OrderInfoOrders.
        :rtype: str
        """
        return self._order

    @order.setter
    def order(self, order: str):
        """Sets the order of this OrderInfoOrders.


        :param order: The order of this OrderInfoOrders.
        :type order: str
        """

        self._order = order

    @property
    def amount(self) -> int:
        """Gets the amount of this OrderInfoOrders.


        :return: The amount of this OrderInfoOrders.
        :rtype: int
        """
        return self._amount

    @amount.setter
    def amount(self, amount: int):
        """Sets the amount of this OrderInfoOrders.


        :param amount: The amount of this OrderInfoOrders.
        :type amount: int
        """

        self._amount = amount
