# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class TradeBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, csv_file: str=None):  # noqa: E501
        """TradeBody - a model defined in Swagger

        :param csv_file: The csv_file of this TradeBody.  # noqa: E501
        :type csv_file: str
        """
        self.swagger_types = {
            'csv_file': str
        }

        self.attribute_map = {
            'csv_file': 'csv_file'
        }
        self._csv_file = csv_file

    @classmethod
    def from_dict(cls, dikt) -> 'TradeBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The trade_body of this TradeBody.  # noqa: E501
        :rtype: TradeBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def csv_file(self) -> str:
        """Gets the csv_file of this TradeBody.


        :return: The csv_file of this TradeBody.
        :rtype: str
        """
        return self._csv_file

    @csv_file.setter
    def csv_file(self, csv_file: str):
        """Sets the csv_file of this TradeBody.


        :param csv_file: The csv_file of this TradeBody.
        :type csv_file: str
        """

        self._csv_file = csv_file
